linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  revive:
    rules:
      - name: unused-parameter
      - name: context-as-argument

  gocyclo:
    min-complexity: 15

  staticcheck:
    checks: ["all"]

  dupl:
    threshold: 100

linters:
  enable:
    - errcheck
    - revive       # Заменяет golint
    - staticcheck
    - gocyclo
    - dupl
    - gofmt

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo